### ISSUE TITLE
Instructions to expose minio loadbalancer to virtual machine running in AWS or Azure

### ISSUE THREAD

**Issue by uzfarid** [k8-proxy/p-k8-jmeter-test-engine#113]

**Comment by shashanksinha89** [comment]
Steps to expose minio via LB

- Create load-balancer service for `minio`. Create `minio-lb.yaml` and paste below content

```
apiVersion: v1
kind: Service
metadata:
  name: minio-lb-svc
  namespace: minio
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: minio
  loadBalancerSourceRanges:
  - <MY_EXTERNAL_IP>
```
